<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="AASHYD-847B8Y2" failures="1" tests="1" name="com.advrt.testcases.AD_Setup_Admin" time="29.645" errors="0" timestamp="2024-03-22T11:15:04 IST" skipped="0">
  <testcase classname="com.advrt.testcases.AD_Setup_Admin" name="Setup_Audit_011" time="29.645">
    <failure message="The following asserts failed:
	FAIL: delete setup details is not audited expected [Setup : &quot;manual 1 min sampling&quot;  deleted by User ID : &quot;Kaverib&quot;, User Name : &quot;Kaveri Bedar&quot;] but found [Setup : &quot;Manual 5 sec SR&quot;  deleted by User ID : &quot;Kaverib&quot;, User Name : &quot;Kaveri Bedar&quot;]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
FAIL: delete setup details is not audited expected [Setup : "manual 1 min sampling"  deleted by User ID : "Kaverib", User Name : "Kaveri Bedar"] but found [Setup : "Manual 5 sec SR"  deleted by User ID : "Kaverib", User Name : "Kaveri Bedar"]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.advrt.testcases.AD_Setup_Admin.Setup_Audit_011(AD_Setup_Admin.java:967)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Setup_Audit_011 -->
</testsuite> <!-- com.advrt.testcases.AD_Setup_Admin -->
